### ISSUE TITLE
Freedraw

### ISSUE THREAD

**Issue by srinisubramanian** [ailon/markerjs#26]
Any plan to provide a free drawing annotation? Just tap on image and draw any shape?

**Comment by ailon** [comment]
Not in a foreseeable future. Sorry.

**Comment by pazoozooCH** [comment]
Hi @ailon . We're looking for an image annotation tool. marker.js looks very promising, but the missing free draw functionality is unfortunate.

Mind to elaborate on why this isn't on the roadmap (no time, too difficult, ...)?

**Comment by ailon** [comment]
@pazoozooCH it would be just a totally different workflow since currently a marker is added on a toolbar click and then you can manipulate it. This obviously wouldn't work for the free drawing scenario. I'm kicking the tires on v.2 though, and the ability to draw is one of the must-haves for that. No ETA on that.
